
include $(SIMSCRIPTS_DIR)/mkfiles/plusargs.mk

TB=mor1kx_soc_gate_uvm_tb

# Suppress missing timescale error
VSIM_FLAGS += -suppress 3009

include $(SIMSCRIPTS_DIR)/mkfiles/common_sim.mk


	